# this is an example, please modify

PLCAddress: 192.168.0.2
PLCRack: 0
PLCSlot: 0
ReadRateMs: 1000
DBReads:
  - DBNumber: 900
    DBOffsetByte: 0
    DBLengthByte: 16
    Tags:
      - Name: Example1
        MetricsName: mysystem_example1_count
        OffsetByte: 0
        Type: Int64
      - Name: Example3
        MetricsName: mysystem_example2_count
        OffsetByte: 8
        OffsetBit: 4
        Type: Bool
  - DBNumber: 901
    DBOffsetByte: 0
    DBLengthByte: 200
    Tags:
      - Name: Example4
        MetricsName: mysystem_example3_string
        OffsetByte: 8
        StringLength: 20
        Type: String